### ISSUE TITLE
What do loopCounter mean in loadwavfile?

### ISSUE THREAD

**Issue by KYShek** [MerlynMind/kotlin_speech_features#2]
I see there is a loop in demo.ui.MainViewModel.loadWavFIle. I can't figure out why 

`for (i in 0 until loopCounter)`
is necessary when reading a wave.
I deleted the loop and it seems no differences for mfcc features.

**Comment by alamkanak** [comment]
You are correct. Good catch. Looks like the loop function does not play a role here other than increasing number of operations. Feel free to remove it.
