### ISSUE TITLE
If winfunc = np.hamming, how should I handle it?

### ISSUE THREAD

**Issue by Java1987** [MerlynMind/kotlin_speech_features#3]
Hello, thank you for creating this library. As mentioned, if winfunc = np.hamming, what should I do? Thank you.

**Comment by alamkanak** [comment]
Since kotlin does not have numpy, there is no built in hamming function in kotlin. However, the mfcc function in kotlin speech features has an argument called winFunc. You can pass in any array in there. So you can manually construct the hamming array and pass it to mfcc function.

**Comment by Java1987** [comment]
Thanks very much，I have resolved this problem.

private fun hamming(m: Int): FloatArray {
    return when {
        m <= 0 -> floatArrayOf()
        m == 1 -> floatArrayOf(1.0f)
        else -> FloatArray(m) { n ->
            (0.54 - 0.46 * cos(2.0 * Math.PI * n / (m - 1))).toFloat()
        }
    }
}


________________________________
发件人: Raquib-ul Alam (Kanak) ***@***.***>
发送时间: 2024年6月2日 5:21
收件人: MerlynMind/kotlin_speech_features ***@***.***>
抄送: SilveyZhang ***@***.***>; Author ***@***.***>
主题: Re: [MerlynMind/kotlin_speech_features] If winfunc = np.hamming, how should I handle it? (Issue #3)


Since kotlin does not have numpy, there is no built in hamming function in kotlin. However, the mfcc function in kotlin speech features has an argument called winFunc. You can pass in any array in there. So you can manually construct the hamming array and pass it to mfcc function.

―
